version: '3'

services:
  # app:
  #   build: .
  #   command: ./.docker/start.sh
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
